inputs:
  #     - Stdin:{}
  - Kafka:
      topic:
          logs: 1
      #assign:
      #  server_log01: [0,1,2,3]
      codec: json
      consumer_settings:
        bootstrap.servers: "10.25.157.28:31090,10.25.157.28:31091,10.25.157.28:31092"
        group.id: logs
        from.beginning: 'true'
        max.partition.fetch.bytes: '10485760'
        auto.commit.interval.ms: '5000'
filters:
  - Grok:
      src: message
      match:
        - '^(?P<logtime>\S+ \S+) (?P<appname>\w+)'
      remove_fields: ["logtime"]
outputs:
  - 'plugin/logbackkafka/logbackkafka.so': {}